postgres:
  host: "postgres"
  port: 5432
  username: "task-user"
  password: "task-password"
  database: "task"
  max_conns: 10
  min_conns: 2

api:
  host: scoring-service
  port: 50051

redis:
  addr: "my_redis_container:6379"
  password: ""
  user: ""
  db: 0
  max_retries: 5
  dial_timeout: 5
  timeout: 3

kafka:
  brokers:
    - kafka1:29091
    - kafka2:29092
    - kafka3:29093
